version: "3"

services:
  node_app:
    container_name: node_app
    build: .
    image: node_app
    ports:
      - "2020:2020"
    environment:
      - PG_DB=node_db
      - PG_USER=Gabriel
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - mongo
  

  #node_db:
   # container_name: node_db
    #image: postgres:15
    #ports:
     # - "5432:5432"
    #environment:
     # - POSTGRES_DB=node_db
      #- POSTGRES_USER=Gabriel
      #- POSTGRES_PASSWORD=12345
   # volumes:
    #  - node_db_data:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password

    


